language: go
go:
    - 1.10.x
    - 1.11.x
    - 1.12.x
    - master
os:
    - linux
    - osx
dist: trusty
sudo: false
install: true
script:
    - cd ./examples
    - env GO111MODULE=on go build
    - env GO111MODULE=on go test -v